apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: vcluster
spec:
  workerClusterResources:
  xaasRequestPipeline:
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: vclusters.example.promise
    spec:
      group: example.promise
      scope: Namespaced
      names:
        plural: vclusters
        singular: vcluster
        kind: vcluster
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name:
                    type: string
