apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: otelcol-ls
spec:
  workerClusterResources:
  xaasRequestPipeline:
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: otelcol.example.promise
    spec:
      group: otelcol.example.promise
      scope: Namespaced
      names:
        plural: otelcol
        singular: otelcol
        kind: otelcol
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  name:
                    type: string
